export const BRAND_COLORS = {
  PRIMARY: "#4527A0",
  PRIMARY_LIGHT: "#7E57C2",
  PRIMARY_DARK: "#311B92",
  SECONDARY: "#1565C0",
  ACCENT_MINT: "#FF7043",
  ACCENT_YELLOW: "#42A5F5",
  SUCCESS: "#43A047",
  WARNING: "#FFB300",
  DANGER: "#E53935",
  BACKGROUND: "#FAFAFA",
  SURFACE: "#FFFFFF",
  SURFACE_MUTED: "#F5F5F5",
  BORDER_LIGHT: "#E0E0E0",
  BORDER_DARK: "#B0BEC5",
  TEXT_PRIMARY: "#424242",
  TEXT_SECONDARY: "#757575",
  PLACEHOLDER: "#B0BEC5",
  ICON_PRIMARY: "#4527A0",
  ICON_SECONDARY: "#90A4AE",
} as const;

export const TAB_GRADIENTS = {
  index: [BRAND_COLORS.PRIMARY, BRAND_COLORS.PRIMARY_LIGHT],
  search: [BRAND_COLORS.ACCENT_YELLOW, BRAND_COLORS.SECONDARY],
  notifications: [BRAND_COLORS.ACCENT_MINT, BRAND_COLORS.PRIMARY],
  messages: [BRAND_COLORS.ACCENT_YELLOW, BRAND_COLORS.ACCENT_MINT],
  profile: [BRAND_COLORS.PRIMARY, BRAND_COLORS.PRIMARY_DARK],
} as const;

export const TAB_CONFIG = {
  BORDER_RADIUS: 60, // Reduced and scaled in components
  ICON_SIZE_ACTIVE: 28,
  ICON_SIZE_INACTIVE: 22,
  CONTAINER_HEIGHT: 70,
  ICON_CONTAINER_SIZE: 56,
  SHADOW_ELEVATION: 12,
  BLUR_INTENSITY: 60,
} as const;
